// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideolandAssignment.Models;

namespace VideolandAssignment.Migrations
{
    [DbContext(typeof(VideolandAssignmentContext))]
    partial class VideolandAssignmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("VideolandAssignment.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("VideolandAssignment.Models.Show", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("VideolandAssignment.Models.ShowPerson", b =>
                {
                    b.Property<long>("PersonId");

                    b.Property<long>("ShowId");

                    b.HasKey("PersonId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowPersons");
                });

            modelBuilder.Entity("VideolandAssignment.Models.UnixTimeStamp", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("UnixTimeStamps");
                });

            modelBuilder.Entity("VideolandAssignment.Models.ShowPerson", b =>
                {
                    b.HasOne("VideolandAssignment.Models.Person", "Person")
                        .WithMany("ShowPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VideolandAssignment.Models.Show", "Show")
                        .WithMany("ShowPeople")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
